import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const inter = Montserrat({ subsets: ["latin"] });
import Navigation from "@/ui/Navigation";
import Footer from "@/ui/Footer";
import MiniAddBanner from "@/ui/MiniAddBanner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-main text-titleColor m-auto`}>
        <MiniAddBanner>enjoy free shipping on all orders</MiniAddBanner>

        <Navigation />
        <main className="m-auto w-full h-screenHeight border border-red-500 max-w-screen-2xl px-6 py-8">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
